### ISSUE TITLE
_wp_post_revision_meta_keys isn't a function

### ISSUE THREAD

**Issue by rmccue** [adamsilverstein/wp-post-meta-revisions#1]
`_wp_post_revision_meta_keys()` is used a few times, but because of the class, it's actually a method.

I'd recommend using a namespace instead, as this will make it work a little more nicely. :) (It will drop compat with 5.2, but only when testing using the plugin. This means less changes between the patch and the plugin too, since it should only require adding/removing the single line for the namespace.)

**Comment by bobbravo2** [comment]
I'm not a contributor to the plugin, but I'm pretty sure the goal of it is to integrate it with WordPress core. That being said, I totally agree about adding namespace support, however, we're stuck until WordPress core deprecates php 5.2
[See the discussion on make.wordpress.org](https://wordpress.org/ideas/topic/drop-support-for-php-52)

**Comment by rmccue** [comment]
> I'm not a contributor to the plugin, but I'm pretty sure the goal of it is to integrate it with WordPress core. That being said, I totally agree about adding namespace support, however, we're stuck until WordPress core deprecates php 5.2

My point here was more to have it in a namespace only in this plugin, which means that the core patch would be exactly the same minus the namespace. Right now, it's in a class, which means you *have* to change each call to `$this->`, meaning a large diff with the core patch.

**Comment by bobbravo2** [comment]
gotchya. 

Core could still call it via `do_action('foobar', array($this, '_wp_post_revision_meta_keys');` though, right? Please help me understand in more concrete terms what you are suggesting. Thanks!

**On second thought...** I re-read the code. I believe the [method _wp_post_revision_meta_keys()](https://github.com/adamsilverstein/wp-post-meta-revisions/blob/master/wp-post-meta-revisions.php#L123) should be @visibility private, because there is a `apply_filters( 'wp_post_revision_meta_keys', array() ); ` public filter that should be (in theory at least) the only public interface for the class. 

Thoughts?

**Comment by adamsilverstein** [comment]
@rmccue Thanks for the feedback; apparently I missed all this activity :) 

I like your suggestion of adding a namespace for the plugin, hadn't gotten as far as thinking about the core merge, thanks for bringing that up!

**Comment by adamsilverstein** [comment]
Feedback noted, closing.
