### ISSUE TITLE
add_metadata without delete_metadata?

### ISSUE THREAD

**Issue by sc0ttkclark** [adamsilverstein/wp-post-meta-revisions#22]
This case has no delete_metadata: https://github.com/adamsilverstein/wp-post-meta-revisions/blob/master/wp-post-meta-revisions.php#L133

While this case does: https://github.com/adamsilverstein/wp-post-meta-revisions/blob/master/wp-post-meta-revisions.php#L62

Was there a specific reason delete_metadata was excluded?

**Comment by adamsilverstein** [comment]
@sc0ttkclark Thanks for the question... The reason is: the context is different.

In the second case in the context is the function `_wp_save_revisioned_meta_fields` which is hooked on `_wp_put_post_revision` and is triggered right after core has created a new revision. In this case we can be sure we are attaching meta to a brand new revision and no meta needs to be deleted.

In the first case, the context is is the function `_wp_autosave_post_revisioned_meta_fields` which is hooked on `wp_creating_autosave`. In this case the autosave being updated may be an existing post and may have existing metadata, so we need to delete it first.

Hope that makes sense, thanks for checking out the plugin.

Closing, please re-open if you have any more questions.
