### ISSUE TITLE
Improve QA setup

### ISSUE THREAD

**Issue by jrfnl** [adamsilverstein/wp-post-meta-revisions#44]
Originally from: https://github.com/adamsilverstein/wp-post-meta-revisions/pull/43#issuecomment-473306474

I've had a quick look and would like to propose the following:
1. Do the whole fixing in a separate PR.
    Existing open PRs will need to be rebased after that PR has been merged, so those will be tested properly.
2. Do it with a holistic look at the whole devops setup.

Having said that, I'm looking at:
* Adding a `.gitignore` file.
* Adding a `.gitattributes` file.
* Adding a `composer.json` file.
* Actually running the unit tests in Travis.
* Linting against various PHP versions in Travis.
* Running PHPCS in Travis. I propose to run against the `WordPress-Extra` or `WordPress` ruleset, as well the `PHPCompatibilityWP` ruleset.

Questions:
* What do you think about the above proposal in the first place ?
* Any feedback on the proposed PHPCS rulesets ?
* What is the minimum PHP version you want to support at this moment ? 5.2 still ?
* What is the minimum WP version you want to support ?

I may have additional questions once I start setting things up.

**Comment by adamsilverstein** [comment]
> Do it with a holistic look at the whole devops setup.

That is great, I remember when I set this repo up feeling it was an achievement to get Travis working correctly. II had some help and I believe we wound up using wp-cli plugin scaffold command to start.

> What do you think about the above proposal in the first place ?

Lovely, I appreciate the help! I've left this repository languishing for far too long!

I did add a .gitignore file and get phpunit tests running in https://github.com/adamsilverstein/wp-post-meta-revisions/pull/43 - now I can work on adding more tests and reviewing open PRs.

> Any feedback on the proposed PHPCS rulesets ?

Ruleset proposal seems good.

> What is the minimum PHP version you want to support at this moment ? 5.2 still ?

Since this is a plugin I'd like to consider merging to core at some point, I'd like to keep minimum PHP standards at core's which I think is still 5.2 for a bit longer, but changing to 5.4 later this year? we can skip right to 5.4 if that is the case. You probably know already what this is, if not I'll track down the post. 

> What is the minimum WP version you want to support ?

a few versions back, 4.7 or 4.8.

**Comment by jrfnl** [comment]
Core will change to PHP 5.6 minimum in the near future and PHP 7.? by the end of the year.

**Comment by jrfnl** [comment]
Some more questions:
* Do you check code coverage ?
* License I presume is GPL v2 ?

**Comment by jrfnl** [comment]
And more:
* Could you tell me what the one build having the `WP_TRAVIS_OBJECT_CACHE=true` environment variable set ?
* And what is the `WP_TRAVISCI=travis:js` for ?

**Comment by jrfnl** [comment]
@adamsilverstein I've send in a first series of CS related fixes. Once those are merged, I have four more PRs waiting (not pulling those yet as they would conflict).

Once that's done, I can pull the PR to sort out this issue, though the build will not (yet) pass at that time.

What's left after the above mentioned pulls, are 24 CS violations which either need a decision on whether or not to fix those or would benefit from someone who has actually worked on the code making the fixes.

I can post a detailed list once the pulls have been merged (line numbers would be off otherwise).

**Comment by adamsilverstein** [comment]
OK, getting back to this now @jrfnl, apologies for the delay.

A few answers, responses:

* 5.6 min fine
* GPL v2 "or later"

> Do you check code coverage

* not yet
> WP_TRAVIS_OBJECT_CACHE & WP_TRAVISCI

These come from the wp-cli scaffolding and I think are used as flags by travis or the core unit tests, I'm not certain - I'll have to dig to figure that out.

**Comment by jrfnl** [comment]
Pulled the next one of the "clean-up" series, rest would conflict again, so more waiting in the wings.
