### ISSUE TITLE
Wordpress 5.8.2?

### ISSUE THREAD

**Issue by tomelsj** [adamsilverstein/wp-post-meta-revisions#65]
What's the status of this plugin for Wordpress 5.8.2? Does it work?

Also the plug in page https://wordpress.org/plugins/wp-post-meta-revisions/#description seems to not be up to date.

**Comment by dbareis** [comment]
Doesn't seem to work for Wordpress 6.2...

**Comment by adamsilverstein** [comment]
> Doesn't seem to work for Wordpress 6.2...

Can you clarify, did you test and it didn't work? It should work with the current version?


> Also the plug in page wordpress.org/plugins/wp-post-meta-revisions/#description seems to not be up to date.

I will test and get the plugin page updated

**Comment by adamsilverstein** [comment]
updated the plugin on wp.org. I tested and it worked for me other than the already known "off by one" issue. 

Given the recent work on footnotes, I feel we have new justification to consider this for core and I plan to work on adding it there.

See https://github.com/WordPress/gutenberg/pull/52686

**Comment by dbareis** [comment]
> > Doesn't seem to work for Wordpress 6.2...
> 
> Can you clarify, did you test and it didn't work? It should work with the current version?

@adamsilverstein 
I definitely installed or tested, otherwise how would I know?

I probably could have expanded on that,  I was probably hoping on a quick response saying it does work before investing any more time on it.  By now, I've forgotten the issue and written also plugin to do this.  At the time my site may have been having a weird issue and that may have been the cause of any issues.
